StarPlatinum:
  cooldown: 5
  damage: 1.0
  hits: 5
  knockback: 0.3
TheWorld:
  cooldown: 240        # This cooldown is for stopping time
  cooldown_p: 5        # This cooldown is for punch
  time_duration: 5
  damage: 1.0
  hits: 5
  knockback: 0.3
CrazyDiamond:
  cooldown: 15
  time_duration: 10
  amplifier: 0
MagicianRed:
  cooldown: 30
  fireball_speed: 2.0
  damage: 3.0
  fireball_count: 3
HermitPurple:
  cooldown: 20
  vine_length: 4
  pull_strength: 1.3
  damage: 3.0
KillerQueen:
  cooldown: 120
  explosion_power: 2.0
  explosion_delay: 3
NovemberRain:
  cooldown: 600
  radius: 10
  duration: 5
  damage: 2.0
SilverChariot:
  cooldown: 5
  damage: 0.5
  hits: 7
  knockback: 0.2
Tusk:
  cooldown: 15
  damage: 3.0
HierophantGreen:
  cooldown: 30
  damage: 1.0
  ammo_count: 3
HeavensDoor:
  cooldown: 120
  damage: 1.0
  duration: 30